name: flutter_firebase_02
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  fl_chart: ^0.64.0
  intl: ^0.18.1
  dio: ^5.3.4

  flutter_dotenv: ^5.1.0
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

    - ./lib/images/
    - ./lib/images/home/
    - ./lib/images/account/

    - ./lib/images/register/
    - ./lib/images/register/avatars/

    - ./lib/images/weather/
    - ./lib/images/weather/essentials/
