import 'package:intl/intl.dart';

import './weather/daily/weather_daily_essentials_model.dart';
import './weather/daily/weather_daily_hourly_model.dart';

import './weather/weather_location_model.dart';
import './weather/weather_temperature_model.dart';
import './weather/weather_weekly_model.dart';
import './weather/weather_daily_model.dart';

class WeatherModel {
  const WeatherModel({
    required this.location,
    required this.temperature,
    required this.weekly,
    required this.daily,
  });

  final WeatherLocationModel location;
  final WeatherTemperatureModel temperature;
  final List<WeatherWeeklyModel> weekly;
  final List<WeatherDailyModel> daily;
}

final weather = WeatherModel(
  location: WeatherLocationModel(
    location: "Toronto Ontario",
    date: DateFormat("d MMM").format(DateTime.now()),
  ),
  temperature: const WeatherTemperatureModel(
    temperature: "36",
    condition: "Partially Cloudy",
    image: "./lib/images/weather/clear-day.png",
  ),
  weekly: [
    const WeatherWeeklyModel(
      image: "./lib/images/weather/clear-day.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/clear-night.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/cloudy.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/hail.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/rain.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/snow-showers.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/snow.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
  ],
  daily: [
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/rain.png",
              title: "Rain",
              value: "100%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/humidity.png",
              title: "Humidity",
              value: "85%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/wind.png",
              title: "Wind",
              value: "10ms",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/home/weather/dew.png",
              title: "Dew",
              value: "20.8%",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/pressure.png",
              title: "Pressure",
              value: "1012.4mb",
            ),
            EssentialBlockModel(
              image: "./lib/images/home/weather/cloud.png",
              title: "Cover",
              value: "50.2%",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "00",
          temperature: "10",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "01",
          temperature: "80",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "02",
          temperature: "20",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "03",
          temperature: "70",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "04",
          temperature: "25",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "05",
          temperature: "65",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "06",
          temperature: "30",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "07",
          temperature: "60",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "08",
          temperature: "35",
          precipitation: "60",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "09",
          temperature: "55",
          precipitation: "50",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "10",
          temperature: "40",
          precipitation: "70",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "11",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "12",
          temperature: "50",
          precipitation: "10",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "95",
          precipitation: "85",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "14",
          temperature: "18",
          precipitation: "80",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "15",
          temperature: "74",
          precipitation: "90",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "16",
          temperature: "32",
          precipitation: "20",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "17",
          temperature: "54",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "18",
          temperature: "33",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "19",
          temperature: "65",
          precipitation: "40",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "20",
          temperature: "87",
          precipitation: "15",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "21",
          temperature: "98",
          precipitation: "25",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "22",
          temperature: "35",
          precipitation: "30",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "23",
          temperature: "23",
          precipitation: "34",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/home/weather/humidity.png",
          hour: "24",
          temperature: "18",
          precipitation: "22",
          pressure: "1012.4",
          humidity: "85",
          cover: "50.2",
          dew: "20.8",
          wind: "10",
        ),
      ],
    ),
  ],
);
