import 'package:intl/intl.dart';

import './weather/daily/weather_daily_essentials_model.dart';
import './weather/daily/weather_daily_hourly_model.dart';

import './weather/weather_location_model.dart';
import './weather/weather_temperature_model.dart';
import './weather/weather_weekly_model.dart';
import './weather/weather_daily_model.dart';

class WeatherModel {
  const WeatherModel({
    required this.location,
    required this.temperature,
    required this.weekly,
    required this.daily,
  });

  final WeatherLocationModel location;
  final WeatherTemperatureModel temperature;
  final List<WeatherWeeklyModel> weekly;
  final List<WeatherDailyModel> daily;
}

final dummyWeather = WeatherModel(
  location: WeatherLocationModel(
    location: "Toronto Ontario",
    longitude: "73.8057",
    latitude: "15.4584",
    timezone: "Asia/Kolkata",
    date: DateFormat("d MMM").format(DateTime.now()),
  ),
  temperature: const WeatherTemperatureModel(
    temperature: "36",
    condition: "Partially Cloudy",
    image: "./lib/images/weather/clear-day.png",
  ),
  weekly: [
    const WeatherWeeklyModel(
      image: "./lib/images/weather/clear-day.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/clear-night.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/cloudy.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/hail.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/rain.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/snow-showers.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
    const WeatherWeeklyModel(
      image: "./lib/images/weather/snow.png",
      condition: "Partially Cloudy",
      temperature: "36",
      day: "Thursday",
      date: "16 Nov",
    ),
  ],
  daily: [
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
    WeatherDailyModel(
      location: WeatherLocationModel(
        location: "Toronto Ontario",
        longitude: "73.8057",
        latitude: "15.4584",
        timezone: "Asia/Kolkata",
        date: DateFormat("d MMM, EEEE").format(DateTime.now()),
      ),
      temperature: const WeatherTemperatureModel(
        temperature: "36",
        condition: "Partially Cloudy",
        image: "./lib/images/weather/clear-day.png",
      ),
      essentials: [
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/rain.png",
              title: "Rain",
              value: "100",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/humidity.png",
              title: "Humidity",
              value: "85",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/wind.png",
              title: "Wind",
              value: "10",
            ),
          ],
        ),
        const WeatherDailyEssentialsModel(
          blocks: [
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/dew.png",
              title: "Dew",
              value: "20.8",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/pressure.png",
              title: "Pressure",
              value: "1012.4",
            ),
            EssentialBlockModel(
              image: "./lib/images/weather/essentials/cloud.png",
              title: "Cover",
              value: "50.2",
            ),
          ],
        ),
      ],
      hourly: [
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "00",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "01",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "02",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "03",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "04",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "05",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "06",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "07",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "08",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "09",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "10",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "11",
          temperature: "38",
          precipitation: "35",
          pressure: "1005.7",
          humidity: "55",
          cover: "55",
          dew: "37",
          wind: "38",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "12",
          temperature: "32",
          precipitation: "50",
          pressure: "1000",
          humidity: "52.5",
          cover: "52.5",
          dew: "35",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "13",
          temperature: "30",
          precipitation: "50",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-night.png",
          hour: "14",
          temperature: "32",
          precipitation: "55",
          pressure: "1010",
          humidity: "55",
          cover: "55",
          dew: "20",
          wind: "22",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/cloudy.png",
          hour: "15",
          temperature: "35",
          precipitation: "60",
          pressure: "1005",
          humidity: "52.5",
          cover: "52.5",
          dew: "26",
          wind: "27",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/hail.png",
          hour: "16",
          temperature: "37",
          precipitation: "45",
          pressure: "1002.5",
          humidity: "58",
          cover: "54",
          dew: "25",
          wind: "25",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/rain.png",
          hour: "17",
          temperature: "35",
          precipitation: "48",
          pressure: "1000",
          humidity: "50",
          cover: "50",
          dew: "30",
          wind: "28",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow-showers.png",
          hour: "18",
          temperature: "30",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "32.5",
          wind: "30",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/snow.png",
          hour: "19",
          temperature: "32.5",
          precipitation: "55",
          pressure: "1002.5",
          humidity: "52.5",
          cover: "52.5",
          dew: "40",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder-showers.png",
          hour: "20",
          temperature: "36",
          precipitation: "50",
          pressure: "1005",
          humidity: "55",
          cover: "55",
          dew: "35",
          wind: "32.5",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/thunder.png",
          hour: "21",
          temperature: "34",
          precipitation: "48",
          pressure: "999.5",
          humidity: "52.5",
          cover: "55",
          dew: "35.5",
          wind: "37",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/wind.png",
          hour: "22",
          temperature: "37",
          precipitation: "45",
          pressure: "1000.5",
          humidity: "53",
          cover: "57",
          dew: "32",
          wind: "35",
        ),
        const WeatherDailyHourlyModel(
          image: "./lib/images/weather/clear-day.png",
          hour: "23",
          temperature: "35",
          precipitation: "32",
          pressure: "1000",
          humidity: "52.3",
          cover: "52.7",
          dew: "32.2",
          wind: "32.5",
        ),
      ],
    ),
  ],
);
